# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Blog
    url: '#posts'
    weight: 2
  - name: Projects
    url: '#projects'
    weight: 4
  - name: Research
    url: '#featured'
    weight: 3
  - name: CV
    url: 'files/cv.pdf'
    weight: 5
  - name: Contact
    url: '#contact'
    weight: 6
